[package]
name = "prefixsum"
version = "0.1.0"
authors = ["Admin <monthon40@hotmail.com>"]
edition = "2018"

[[bin]]
name = "prefixsum"
path = "src/prefixsum.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "~1.0"
